//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentId { get; set; }
        public Nullable<int> MaKH { get; set; }
        public string DanhGia { get; set; }
        public Nullable<int> MaMenu { get; set; }
        public Nullable<System.DateTime> Createon { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
