//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoiTac
    {
        public int MaDoiTac { get; set; }
        public string TenQuan { get; set; }
        public string DienThoai { get; set; }
        public int MaMenu { get; set; }
        public string Diachi { get; set; }
        public string MatKhau { get; set; }
    
        public virtual Menu Menu { get; set; }
    }
}
